# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8090

# JPA/Hibernate
spring.jpa.database-platform=${HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Thymeleaf
spring.thymeleaf.cache=false